FROM node:20.1.0-alpine3.16

WORKDIR /takemura-lab/frontend

COPY . /takemura-lab/frontend

RUN npm install react-scripts
RUN npm i -S react-router-dom
RUN npm install framer-motion
RUN npm install axios
