version: '3'
services:
  db:
    image: postgres:15.3-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 30

  backend:
    build: ./backend/src
    container_name: fastapi
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    volumes:
      - ./backend:/takemura-lab/backend
    ports:
      - 8080:8000
    tty: true

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/takemura-lab/frontend
    ports:
      - "3000:3000"
    tty: true

volumes:
  postgres_data:
